namespace: envoy-gateway-system
resources:
  - namespace.yaml
helmCharts:
  - repo: oci://docker.io/envoyproxy
    version: v0.0.0-latest
    name: gateway-helm
    releaseName: eg
    includeCRDs: true
