namespace: default
resources:
  - deployment.yaml
  - httproute.yaml
  - service.yaml
  - serviceaccount.yaml
  - gateway.yaml
  - gatewayclass.yaml
  - custom-proxy-config.yaml
  - backend-active.yaml
  - backend-passive.yaml
  - backendtrafficpolicy.yaml
