apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration
  namespace: default
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="test"
    export MINIO_ROOT_PASSWORD="changeme"
    export MINIO_STORAGE_CLASS_STANDARD="EC:2"
    export MINIO_BROWSER="on"
